### PR TITLE
Login UI

### PR DESCRIPTION
**Pull request by SAKSHAM-SUDO**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by SAKSHAM-SUDO** [comment]
WhatsApp Image 2021-10-02 at 9 55 11 AM

**Comment by Akshay0701** [comment]
Wow I like this, Thank you so much @SAKSHAM-SUDO for your contributions,

SAKSHAM-SUDO you added 2 images is there any particular reason?
could you remove the image which you didn;t use?

**Comment by SAKSHAM-SUDO** [comment]
done

**Comment by SAKSHAM-SUDO** [comment]
Please merge this branch so that some errors are removed  and the i will  create a new branch from master.

**Comment by Akshay0701** [comment]
yes, I fixed some code style, LGTM

**Comment by SAKSHAM-SUDO** [comment]
Thanks

**Comment by Akshay0701** [comment]
closed with #19

**Pull request merged**
